#
# example of creating and external service file
# a CNAME record will be created for service
#
kind: Service
apiVersion: v1
metadata:
  name: external-database
spec:
  type: ExternalName
  externalName: "database.company.com"
