apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      name: peer
  clusterIP: None # none here makes this a headless service
  selector:
    app: mongo
