#
# persistent storage to outlast any pod/container
# used to set up a volume backed by an nfs server
# through a PersistenVolumeClaim
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  lavels:
    volume: my-volume
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.1
    path: "/exports"
