apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bernard-tut-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
